--DROP TABLE IF EXISTS CITY;

--CREATE TABLE SPRINKLE (userId INT PRIMARY KEY AUTO_INCREMENT, roomId VARCHAR,
--                      money, INT UNSIGNED, receiveID VARCHAR );

--CREATE TABLE LOOKUP (userId INT PRIMARY KEY AUTO_INCREMENT, roomId VARCHAR,
--                       money, INT UNSIGNED, receiveID VARCHAR );

CREATE TABLE MONEY (Number INT PRIMARY KEY AUTO_INCREMENT, id INT PRIMARY KEY, room VARCHAR, token VARCHAR,
                    sprinkle UNSIGNED INT, sprinkle_time DATE, sprinkle_id VARCHAR,
                    received UNSIGNED INT, received_time DATE, received_id VARCHAR );

--INSERT INTO CITY (NAME, COUNTRY, POPULATION) VALUES ('San Francisco', 'US', 10000);
--INSERT INTO CITY (NAME, COUNTRY, POPULATION) VALUES ('서울', 'KR', 20000);
--INSERT INTO CITY (NAME, COUNTRY, POPULATION) VALUES ('東京', 'JP', 30000);
--INSERT INTO CITY (NAME, COUNTRY, POPULATION) VALUES ('부산', 'KR', 40000);